let movies = [{
        title: "Tapped Out",
        year: 2014,
        categories: ["Action", "Drama", "Sport"],
        summary: "One-time martial arts prodigy Michael Shaw is sentenced to community service at a rundown karate school, where he gets back into the discipline of the sport. During a local MMA fight he encounters the man who killed his family a decade ago, and his decision to get revenge involves going behind his karate master's back to train and compete in the upcoming MMA tournament. When he finally goes toe to toe in the ring with his parents' killer he won't stop until the last punch knocks his opponent to the ground, leaving him TAPPED OUT.",
        imdbId: "tt2361184",
        imdbRating: 5.4,
        runtime: 105,
        language: "English",
        trailer: "https://youtube.com/watch?v=AOfD0rYAVKo",
        bigPoster: "http://i3.ytimg.com/vi/AOfD0rYAVKo/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/AOfD0rYAVKo/hqdefault.jpg",
    },
    {
        title: "Is Genesis History?",
        year: 2017,
        categories: ["Documentary"],
        summary: 'A comprehensive documentary featuring scientists and scholars looking at the world and explaining how it intersects with the history recorded in Genesis. Dr. Del Tackett, creator of "The Truth Project," serves as your guide; hiking through canyons, climbing up mountains, and diving below the surface of the sea in an exploration of two competing views, and one compelling truth.',
        imdbId: "tt6360332",
        imdbRating: 4.1,
        runtime: 100,
        language: "English",
        trailer: "https://youtube.com/watch?v=tudQkA06tTM",
        bigPoster: "http://i3.ytimg.com/vi/tudQkA06tTM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/tudQkA06tTM/hqdefault.jpg",
    },
    {
        title: "Only God Forgives",
        year: 2013,
        categories: ["Action", "Crime", "Drama"],
        summary: "Bangkok. Ten years ago Julian killed a man and went on the run. Now he manages a Thai boxing club as a front for a drugs operation. Respected in the criminal underworld, deep inside, he feels empty. When Julian's brother murders an underage prostitute, the police call on retired cop Chang - the Angel of Vengeance. Chang allows the father to kill his daughter's murderer, then 'restores order' by chopping off the man's right hand. Julian's mother Crystal - the head of a powerful criminal organization - arrives in Bangkok to collect her son's body. She dispatches Julian to find his killers and 'raise hell'.",
        imdbId: "tt1602613",
        imdbRating: 5.7,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=MhRKlwr1-KM",
        bigPoster: "http://i3.ytimg.com/vi/MhRKlwr1-KM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/MhRKlwr1-KM/hqdefault.jpg",
    },
    {
        title: "9 Songs",
        year: 2004,
        categories: ["Action", "Drama", "Music", "Romance"],
        summary: "Matt, a young glaciologist, soars across the vast, silent, icebound immensities of the South Pole as he recalls his love affair with Lisa. They meet at a mobbed rock concert in a vast music hall--London's Brixton Academy. They are in bed at night's end. Together, over a period of several months, they pursue a mutual sexual passion whose inevitable stages unfold in counterpoint to nine live-concert songs.",
        imdbId: "tt0411705",
        imdbRating: 4.8,
        runtime: 71,
        language: "English",
        trailer: "https://youtube.com/watch?v=N1HWcofsxJk",
        bigPoster: "http://i3.ytimg.com/vi/N1HWcofsxJk/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/N1HWcofsxJk/hqdefault.jpg",
    },
    {
        title: "10x10",
        year: 2018,
        categories: ["Thriller"],
        summary: "Lewis (Luke Evans) is an outwardly ordinary guy, but in reality he is hiding an obsession - revenge - against Cathy (Kelly Reilly). Lewis kidnaps Cathy in broad daylight and takes her to his home, where he locks her in a soundproof cell and attempts to extract a dark secret from her past.",
        imdbId: "tt6210996",
        imdbRating: 4.8,
        runtime: 88,
        language: "English",
        trailer: "https://youtube.com/watch?v=PPIHpRUUaro",
        bigPoster: "http://i3.ytimg.com/vi/PPIHpRUUaro/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/PPIHpRUUaro/hqdefault.jpg",
    },
    {
        title: "Shut In",
        year: 2016,
        categories: ["Action", "Drama", "Horror", "Thriller"],
        summary: "A heart-pounding thriller about a widowed child psychologist who lives an isolated existence in rural New England. Caught in a deadly winter storm, she must find a way to rescue a young boy before he disappears forever.",
        imdbId: "tt2582500",
        imdbRating: 4.7,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=KqRdVOQ98k8",
        bigPoster: "http://i3.ytimg.com/vi/KqRdVOQ98k8/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/KqRdVOQ98k8/hqdefault.jpg",
    },
    {
        title: "Sinbad: The Fifth Voyage",
        year: 2014,
        categories: ["Action", "Adventure", "Fantasy"],
        summary: "When the Sultan's first born is taken by an evil sorcerer, Sinbad is tasked with traveling to a desert of magic and creatures to save her.",
        imdbId: "tt1403862",
        imdbRating: 5.8,
        runtime: 89,
        language: "English",
        trailer: "https://youtube.com/watch?v=7UlPEPZFy4o",
        bigPoster: "http://i3.ytimg.com/vi/7UlPEPZFy4o/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/7UlPEPZFy4o/hqdefault.jpg",
    },
    {
        title: "No Good Deed",
        year: 2014,
        categories: ["Action", "Crime", "Drama", "Thriller"],
        summary: "A lonely mother, invites a handsome car accident victim into her home. Desperate for a little attention, she doesn't realize she's entertaining a sociopathic, yet charming escape convict. In one terrorizing night her life completely changes as she fight for her own life and the life of her children in No Good Deed.",
        imdbId: "tt2011159",
        imdbRating: 5.6,
        runtime: 84,
        language: "English",
        trailer: "https://youtube.com/watch?v=VjLVZ4BxOSI",
        bigPoster: "http://i3.ytimg.com/vi/VjLVZ4BxOSI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/VjLVZ4BxOSI/hqdefault.jpg",
    },
    {
        title: "Battle Los Angeles",
        year: 2011,
        categories: ["Action", "Sci-Fi"],
        summary: "Los Angeles and other cities around the world are being bombarded by meteors that seem to be slowing down once they hit the earth's atmosphere. The earth is suddenly being invaded by space aliens that have landed off the shore of LA, and who begin killing everybody along the beach. The military is ordered into action. Marine Staff Sergeant Nantz (Aaron Eckhart), who was about to retire, is reassigned to a new platoon. The platoon, flown by chopper to the forward operating base at Santa Monica Airport, is being led by a new 2nd Lt. Martinez (Ramon Rodriguez). They are sent on a mission to rescue some civilians who are trapped at the police station within alien territory. They only have 3 hours to complete their mission and get out before the Air Force bombs that zone.",
        imdbId: "tt1217613",
        imdbRating: 5.8,
        runtime: 116,
        language: "English",
        trailer: "https://youtube.com/watch?v=0dI94ZO2SbM",
        bigPoster: "http://i3.ytimg.com/vi/0dI94ZO2SbM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/0dI94ZO2SbM/hqdefault.jpg",
    },
    {
        title: "The Monster",
        year: 2016,
        categories: ["Action", "Drama", "Fantasy", "Horror"],
        summary: "Kathy is the alcoholic and smoking addicted mother of the young, but mature teenager Lizzy. They live together since Kathy's husband Roy left her, and she neglects her daughter. Kathy is supposed to drive Lizzy to her father's home in the morning, but she sleeps until late afternoon and they have to travel during a rainy night. While driving through a lonely road through the woods, Kathy hits a wolf that breaks her car, leaving them stranded on the empty road. They call 911 and while waiting for the tow truck and an ambulance, the wolf disappears from the road. When the tow truck arrives, the mechanic Jesse tells that he needs to fix the axle and an oil leakage to tow her car. While repairing the vehicle, a monster attacks him but neither Kathy nor Lizzy note. When they seek Jesse out, they realize that they are not alone in the spot. Further, Kathy learns that monsters do exist. Will they be rescued on time?",
        imdbId: "tt3976144",
        imdbRating: 5.4,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=RUYyqIAiJVc",
        bigPoster: "http://i3.ytimg.com/vi/RUYyqIAiJVc/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/RUYyqIAiJVc/hqdefault.jpg",
    },
    {
        title: "Scorched Earth",
        year: 2018,
        categories: ["Action", "Sci-Fi"],
        summary: "A bounty hunter named Atticus Gage tracks down criminals in a post-apocalyptic Earth.",
        imdbId: "tt2392748",
        imdbRating: 5,
        runtime: 96,
        language: "English",
        trailer: "https://youtube.com/watch?v=fsmldfshBhU",
        bigPoster: "http://i3.ytimg.com/vi/fsmldfshBhU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/fsmldfshBhU/hqdefault.jpg",
    },
    {
        title: "Far Cry 5: Inside Eden's Gate",
        year: 2018,
        categories: ["Drama", "Mystery", "Thriller"],
        summary: "Rumors of a fanatical cult called The Project at Eden's Gate lure three vloggers to remote Hope County, Montana. Following leads of missing locals and other strange events, the three infiltrate the cult. Shocked by what they uncover, they risk everything to warn the world.",
        imdbId: "tt8095034",
        imdbRating: 5.3,
        runtime: 30,
        language: "English",
        trailer: "https://youtube.com/watch?v=_vB-Ir8S_z8",
        bigPoster: "http://i3.ytimg.com/vi/_vB-Ir8S_z8/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/_vB-Ir8S_z8/hqdefault.jpg",
    },
    {
        title: "I Give It a Year",
        year: 2013,
        categories: ["Action", "Comedy", "Romance"],
        summary: "Newlywed couple Nat and Josh are deliriously happy despite their differences, though friends and family aren't convinced that they can last. With their first anniversary approaching and attractive alternatives in the mix, can they last?",
        imdbId: "tt2244901",
        imdbRating: 5.7,
        runtime: 97,
        language: "English",
        trailer: "https://youtube.com/watch?v=YI01PJqVTYE",
        bigPoster: "http://i3.ytimg.com/vi/YI01PJqVTYE/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/YI01PJqVTYE/hqdefault.jpg",
    },
    {
        title: "Bullet",
        year: 2014,
        categories: ["Action", "Crime", "Thriller"],
        summary: "Frank Marasco arrests Kane Cartel who is then sentenced for execution. To stop this, Carlito Kane and Manual Kane kidnap the daughter of the California Governer and Frank's grandson, Mario. Frank Marasco (Bullet) takes law into his own hands to save them.",
        imdbId: "tt2544734",
        imdbRating: 4.7,
        runtime: 87,
        language: "English",
        trailer: "https://youtube.com/watch?v=tdF9Vcv4cCo",
        bigPoster: "http://i3.ytimg.com/vi/tdF9Vcv4cCo/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/tdF9Vcv4cCo/hqdefault.jpg",
    },
    {
        title: "12 Rounds",
        year: 2009,
        categories: ["Action", "Crime", "Mystery", "Thriller"],
        summary: "Uniformed New Orleans PD officer Danny Fisher earns his promotion to detective to his near-rather lucky, albeit brave, arrest of ruthless terrorist arms-dealer Miles Jackson, whose girlfriend Erica Kessen got accidentally killed during the dirty FBI-operation. Exactly a year later, Miles has escaped and blows up Danny's house as foretaste of a Herculean race to accomplish twelve near-impossible tasks against the clock, otherwise his kidnapped wife Molly will be killed. Yet at the end, another master-plan is suspected.",
        imdbId: "tt1160368",
        imdbRating: 5.6,
        runtime: 108,
        language: "English",
        trailer: "https://youtube.com/watch?v=2NvznP_gp_A",
        bigPoster: "http://i3.ytimg.com/vi/2NvznP_gp_A/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/2NvznP_gp_A/hqdefault.jpg",
    },
    {
        title: "Ordinary World",
        year: 2016,
        categories: ["Action", "Comedy", "Drama", "Music"],
        summary: "The mid-life crisis of a husband and father who, on his 40th birthday, decides to revisit his punk-rock past by throwing an extravagant party in the presidential suite of the Drake Hotel - where he encounters his beautiful ex-girlfriend and former bandmates who have since moved on to bigger and better things.",
        imdbId: "tt4189494",
        imdbRating: 5.5,
        runtime: 86,
        language: "English",
        trailer: "https://youtube.com/watch?v=ZV9KzADgkpE",
        bigPoster: "http://i3.ytimg.com/vi/ZV9KzADgkpE/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/ZV9KzADgkpE/hqdefault.jpg",
    },
    {
        title: "Beyond the Edge",
        year: 2018,
        categories: ["Action", "Adventure", "Fantasy"],
        summary: "Contemporary Moscow. A talented gambler gathers a team of people with superpowers to win big at a casino. But at the game he finds himself up against a much stronger mystical rival and ends up in a deadlock putting in danger himself and his team that he has grown to love. To save his friends and his girlfriend the lead character will have to go above and beyond.",
        imdbId: "tt5629524",
        imdbRating: 4.7,
        runtime: 101,
        language: "English",
        trailer: "https://youtube.com/watch?v=_kMp7y9jOxg",
        bigPoster: "http://i3.ytimg.com/vi/_kMp7y9jOxg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/_kMp7y9jOxg/hqdefault.jpg",
    },
    {
        title: "The Con Is On",
        year: 2018,
        categories: ["Comedy"],
        summary: "In an effort to avoid paying off a massive gambling debt to a notorious mobster in England, a couple flees to Los Angeles and hatch a jewel theft plot.",
        imdbId: "tt4685806",
        imdbRating: 3.6,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=-3hucyd-s9U",
        bigPoster: "http://i3.ytimg.com/vi/-3hucyd-s9U/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/-3hucyd-s9U/hqdefault.jpg",
    },
    {
        title: "Bad Ass 2: Bad Asses",
        year: 2014,
        categories: ["Action", "Comedy", "Drama"],
        summary: "Frank Vega teams up with grumpy old agoraphobic Bernie Pope to kick ass and clean up the streets of L.A.",
        imdbId: "tt2996648",
        imdbRating: 5.6,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=XNfeAHF3XQ8",
        bigPoster: "http://i3.ytimg.com/vi/XNfeAHF3XQ8/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/XNfeAHF3XQ8/hqdefault.jpg",
    },
    {
        title: "Wrong Turn 5: Bloodlines",
        year: 2012,
        categories: ["Action", "Horror"],
        summary: "A small West Virginia town is hosting the legendary Mountain Man Festival on Halloween, where throngs of costumed party goers gather for a wild night of music and mischief. But an inbred family of hillbilly cannibals kill the fun when they trick and treat themselves to a group of visiting college students.",
        imdbId: "tt2375779",
        imdbRating: 4.1,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=aeFylL3lLoU",
        bigPoster: "http://i3.ytimg.com/vi/aeFylL3lLoU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/aeFylL3lLoU/hqdefault.jpg",
    },
    {
        title: "Are You Here",
        year: 2013,
        categories: ["Action", "Comedy", "Drama"],
        summary: "Ben Baker is a man-child who lives on his friend's couch getting high. His friend, Steve Dallas, is a moderately successful weather reporter who is living a superficial life. When Ben receives word that his father has died, Steve drives him home and they re-connect with Ben's successful and driven sister Terri and hippie step-mother Angela who is the same age as they are. The reading of the will drives Ben to come up with a new purpose in life, but those around him don't prove to be very supportive, and then they all re-examine their own lives.",
        imdbId: "tt1545754",
        imdbRating: 5.3,
        runtime: 114,
        language: "English",
        trailer: "https://youtube.com/watch?v=uMtNpu6xBvU",
        bigPoster: "http://i3.ytimg.com/vi/uMtNpu6xBvU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/uMtNpu6xBvU/hqdefault.jpg",
    },
    {
        title: "Final Destination 3",
        year: 2006,
        categories: ["Action", "Fantasy", "Horror", "Mystery", "Thriller"],
        summary: "When Wendy Christensen has a vision of an accident on the roller coaster, resulting in her and her friends' deaths, she instantly begins to panic and gets off the ride, causing a few of her friends to get off as well. The remaining friends, including Wendy's boyfriend, are stuck on the roller coaster and find themselves involved in the accident. With death waiting around the corner, Wendy and Kevin Fischer must try and work out death's plan, before they and the remaining survivors end up dead.",
        imdbId: "tt0414982",
        imdbRating: 5.8,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=QdG7A377boY",
        bigPoster: "http://i3.ytimg.com/vi/QdG7A377boY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/QdG7A377boY/hqdefault.jpg",
    },
    {
        title: "Charlie Charlie",
        year: 2016,
        categories: ["Horror"],
        summary: "An Eccentric haunted house owner invites a group of hapless teens to play the terrifying game known as Charlie Charlie, overnight in the many attractions his house has to offer. While the game is meant to be a mere spectacle of spooky fun, it soon turns into a true nightmare leaving the teenagers, and the owner, battling for their lives.",
        imdbId: "tt5156910",
        imdbRating: 2.5,
        runtime: 85,
        language: "English",
        trailer: "https://youtube.com/watch?v=M_tfHlr81yQ",
        bigPoster: "http://i3.ytimg.com/vi/M_tfHlr81yQ/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/M_tfHlr81yQ/hqdefault.jpg",
    },
    {
        title: "Hall Pass",
        year: 2011,
        categories: ["Action", "Comedy", "Romance"],
        summary: "A couple of married guys are always looking at other women. Their wives are fed up with their behavior, and grant them a 'hall pass': a week off their marriage allowing them to do anything. But the guys take their time and their week is almost up. What they don't realize is that at the same time their wives make connections of their own.",
        imdbId: "tt0480687",
        imdbRating: 5.9,
        runtime: 105,
        language: "English",
        trailer: "https://youtube.com/watch?v=1JMCvX6qXuo",
        bigPoster: "http://i3.ytimg.com/vi/1JMCvX6qXuo/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/1JMCvX6qXuo/hqdefault.jpg",
    },
    {
        title: "Welcome to Me",
        year: 2014,
        categories: ["Action", "Comedy", "Drama"],
        summary: "Alice suffers from borderline personality disorder, but she has what she needs in life. She has an apartment, she has a best friend, and she has tapes of every Oprah Winfrey show. And now, after winning the lottery, she also has 83 million dollars. What she doesn't have is an outlet for the whole world to know who she really is. The TV station cut her off when she tried turning her lottery announcement into a frank discussion of her sexual experiences, but with her money in hand, she's off to LA to convince two struggling TV producer brothers to produce her own TV show. Whatever it costs, she's going to do it. From swan entrances to dog neutering, she is going to introduce the world to Alice. But is the world ready for Alice?",
        imdbId: "tt2788716",
        imdbRating: 5.9,
        runtime: 87,
        language: "English",
        trailer: "https://youtube.com/watch?v=r0KEe-hMsLg",
        bigPoster: "http://i3.ytimg.com/vi/r0KEe-hMsLg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/r0KEe-hMsLg/hqdefault.jpg",
    },
    {
        title: "Death Race: Inferno",
        year: 2013,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "Convicted cop-killer Carl Lucas, aka Frankenstein, is a superstar driver in the brutal prison yard demolition derby known as Death Race. Only one victory away from winning freedom for himself and his pit crew, Lucas is plunged into an all-new competition more vicious than anything he has experienced before. Pitted against his most ruthless adversaries ever, Lucas fights to keep himself and his team alive in a race in South Africa's infernal Kalahari Desert. With powerful forces at work behind the scenes to ensure his defeat, will Lucas' determination to win at all costs mean the end of the road for him?",
        imdbId: "tt1988591",
        imdbRating: 5.5,
        runtime: 105,
        language: "English",
        trailer: "https://youtube.com/watch?v=3e2bRLoaUTM",
        bigPoster: "http://i3.ytimg.com/vi/3e2bRLoaUTM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/3e2bRLoaUTM/hqdefault.jpg",
    },
    {
        title: "Date and Switch",
        year: 2014,
        categories: ["Comedy", "Drama", "Romance"],
        summary: "High school seniors Michael and Matty make a pact to help each other lose their virginity before their high school prom. Their plan hits a snag when Matty tells his best friend that he's gay. Michael's supportive but awkward attempts to help Matty fit in put a strain on their decade-long friendship. Their friendship is further tested when Michael falls for Matty's former girlfriend and Matty falls for a guy whom Michael wouldn't approve of. Prom looms and Michael and Matty have to repair their friendship and then figure out their love lives.",
        imdbId: "tt1878942",
        imdbRating: 5.8,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=ggehO3r1hMM",
        bigPoster: "http://i3.ytimg.com/vi/ggehO3r1hMM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/ggehO3r1hMM/hqdefault.jpg",
    },
    {
        title: "The Watch",
        year: 2012,
        categories: ["Action", "Comedy", "Sci-Fi"],
        summary: "In Glenview, Ohio, Evan is the manager of the Costco department store and married to Abby. When the Costco night watchman, Antonio Guzman, is mysteriously murdered, Evan organizes The Neighborhood Watch, a watch team with his suburban neighbors Bob, Franklin and Jamarcus to protect the neighborhood and find the killer of Antonio. Soon they discover that the murderer is an alien that is preparing to invade Earth, and they become the last hope of mankind on Earth.",
        imdbId: "tt1298649",
        imdbRating: 5.7,
        runtime: 102,
        language: "English",
        trailer: "https://youtube.com/watch?v=xCZB2q84jAk",
        bigPoster: "http://i3.ytimg.com/vi/xCZB2q84jAk/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/xCZB2q84jAk/hqdefault.jpg",
    },
    {
        title: "Ghost Rider: Spirit of Vengeance",
        year: 2011,
        categories: ["Action", "Fantasy", "Thriller"],
        summary: "Johnny Blaze, a man who made a deal with the Devil who called himself Mephistopheles at the time (now Roarke), is on the run trying to make sure no-one is harmed by his alter ego, The Ghost Rider. He is approached by a Monk named Moreau who tells him that he can help be him free of the Rider, but first, he needs Johnny's help to protect a boy, whom Roarke has plans for, to help him take human form.",
        imdbId: "tt1071875",
        imdbRating: 4.3,
        runtime: 96,
        language: "English",
        trailer: "https://youtube.com/watch?v=12me4CYA5xA",
        bigPoster: "http://i3.ytimg.com/vi/12me4CYA5xA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/12me4CYA5xA/hqdefault.jpg",
    },
    {
        title: "Jane Got a Gun",
        year: 2015,
        categories: ["Action", "Drama", "Western"],
        summary: "Jane Got a Gun centers on Jane Hammond, who has built a new life with her husband Bill \"Ham\" Hammond after being tormented by the ultra-violent Bishop Boys outlaw gang. She finds herself in the gang's cross-hairs once again when Ham stumbles home riddled with bullets after dueling with the Boys and their relentless mastermind Colin. With the vengeful crew hot on Ham's trail, Jane has nowhere to turn but to her former fiancé Dan Frost for help in defending her family against certain destruction. Haunted by old memories, Jane's past meets the present in a heart-stopping battle for survival.",
        imdbId: "tt2140037",
        imdbRating: 5.9,
        runtime: 98,
        language: "English",
        trailer: "https://youtube.com/watch?v=fm7qxI3gmpw",
        bigPoster: "http://i3.ytimg.com/vi/fm7qxI3gmpw/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/fm7qxI3gmpw/hqdefault.jpg",
    },
    {
        title: "Battle for Skyark",
        year: 2016,
        categories: ["Action", "Adventure", "Family", "Sci-Fi"],
        summary: "When a mysterious race of creatures takes over a desolate Earth, humanity must take refuge in SkyArk, the city in the sky. After the rebellion against a corrupt leadership fails, the wealthy doom the rebels' children to live on the ruins of the old Earth. The rebel leader's son, Rags, must lead his fellow exiles against the monsters in order to have a chance to return to SkyArk, but he soon finds that he has a much greater purpose in saving humanity.",
        imdbId: "tt2784134",
        imdbRating: 2.8,
        runtime: 88,
        language: "English",
        trailer: "https://youtube.com/watch?v=AZH1f572gl4",
        bigPoster: "http://i3.ytimg.com/vi/AZH1f572gl4/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/AZH1f572gl4/hqdefault.jpg",
    },
    {
        title: "Spinning Man",
        year: 2018,
        categories: ["Drama", "Mystery", "Thriller"],
        summary: "Evan Birch is a family man and esteemed professor at a distinguished college, where his charm and reputation have made his philosophy class very popular. When a female student named Joyce goes missing, Evan's previous off-campus dalliances make his wife question his alibi. Gruff police Detective Malloy has even more reason to be suspicious when crucial evidence makes Evan the prime suspect in Joyce's disappearance. Suddenly, the questions Evan faces aren't merely academic - they're a matter of life or death.",
        imdbId: "tt5616294",
        imdbRating: 5.5,
        runtime: 100,
        language: "English",
        trailer: "https://youtube.com/watch?v=91MWq3h2SBM",
        bigPoster: "http://i3.ytimg.com/vi/91MWq3h2SBM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/91MWq3h2SBM/hqdefault.jpg",
    },
    {
        title: "Bounty Killer",
        year: 2013,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "It's been 20 years since the corporations took over the world's governments. Their thirst for power and profits led to the corporate wars, a fierce global battle that laid waste to society as we know it. Born from the ash, the Council of Nine rose as a new law and order for this dark age. To avenge the corporations' reckless destruction, the Council issues death warrants for all white collar criminals. Their hunter's - the BOUNTY KILLER. From amateur savage to graceful assassin, the BOUNTY KILLER'S now compete for body count, fame and a fat stack of cash. They're ending the plague of corporate greed by exterminating the self serving CEO and providing the survivors of the apocalypse with retribution. These are the new heroes. This is the age of the BOUNTY KILLER.",
        imdbId: "tt2369396",
        imdbRating: 5.5,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=ciGAjiPlvYk",
        bigPoster: "http://i3.ytimg.com/vi/ciGAjiPlvYk/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/ciGAjiPlvYk/hqdefault.jpg",
    },
    {
        title: "A Single Shot",
        year: 2013,
        categories: ["Action", "Crime", "Drama", "Thriller"],
        summary: "The tragic death of a beautiful young girl starts a tense and atmospheric game of cat and mouse between hunter John Moon and the hardened backwater criminals out for his blood.",
        imdbId: "tt1540741",
        imdbRating: 5.8,
        runtime: 116,
        language: "English",
        trailer: "https://youtube.com/watch?v=3M8KJ7E_yWs",
        bigPoster: "http://i3.ytimg.com/vi/3M8KJ7E_yWs/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/3M8KJ7E_yWs/hqdefault.jpg",
    },
    {
        title: "Hangman",
        year: 2017,
        categories: ["Crime", "Mystery", "Thriller"],
        summary: "Decorated homicide detective Ray Archer (Al Pacino) and his partner, criminal profiler Will Ruiney, (Karl Urban) are tasked to catch one of the city's notoriously vicious serial killers who is playing a twisted version of murder using the child's game - HANGMAN, while crime journalist Christi Davies (Brittany Snow) reports on the crime spree, shadowing the detectives.",
        imdbId: "tt3011960",
        imdbRating: 5.2,
        runtime: 0,
        language: "English",
        trailer: "https://youtube.com/watch?v=CNhLBNG-dUg",
        bigPoster: "http://i3.ytimg.com/vi/CNhLBNG-dUg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/CNhLBNG-dUg/hqdefault.jpg",
    },
    {
        title: "The Forest",
        year: 2016,
        categories: ["Action", "Horror", "Mystery", "Thriller"],
        summary: "A woman goes into Japan's Suicide Forest to find her twin sister, and confronts supernatural terror.",
        imdbId: "tt3387542",
        imdbRating: 4.8,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=RBc5YcuOThY",
        bigPoster: "http://i3.ytimg.com/vi/RBc5YcuOThY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/RBc5YcuOThY/hqdefault.jpg",
    },
    {
        title: "The Cure",
        year: 2014,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "The film is about a young female researcher whose life is in danger when she discovers the pharmaceutical company she works for had developed a cure for cancer many years earlier. They haven't released it because that would destroy their chemotherapy drug sales. She must now escape and release the cure to world while the company tries to stop her.",
        imdbId: "tt2175947",
        imdbRating: 3.5,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=2dz9pE6EEEU",
        bigPoster: "http://i3.ytimg.com/vi/2dz9pE6EEEU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/2dz9pE6EEEU/hqdefault.jpg",
    },
    {
        title: "The Canal",
        year: 2014,
        categories: ["Action", "Horror", "Mystery", "Thriller"],
        summary: "Film archivist David (Rupert Evans) has been having a rough time lately, as he suspects that his wife Alice (Hannah Hoekstra) has been cheating on him with Alex (Carl Shaaban), one of her work clients. This stress is compounded when David's work partner Claire (Antonia Campbell-Hughes) gives him a reel of to-be-archived footage that shows that his house was the setting for a brutal murder in 1902. Becoming progressively more unsettled and unhinged, David begins to believe that a spectral presence is in his house and ends up following his wife to a nearby canal, where he discovers that she is indeed having an affair with Alex. When Alice goes missing shortly afterwards, David contacts the police- only to become the prime suspect in her disappearance. As the police grow more convinced that David has murdered his wife, he struggles to find proof of his growing suspicion that something otherworldly was instead responsible.",
        imdbId: "tt2517658",
        imdbRating: 5.9,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=5tt6C_X_8wA",
        bigPoster: "http://i3.ytimg.com/vi/5tt6C_X_8wA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/5tt6C_X_8wA/hqdefault.jpg",
    },
    {
        title: "Atlantic Rim: Resurrection",
        year: 2018,
        categories: ["Action", "Sci-Fi"],
        summary: "Los Angeles is under attack by monsters. The mechs attempting to fight them off are better armed than their precursors, but so are the creatures.",
        imdbId: "tt7963218",
        imdbRating: 1.7,
        runtime: 86,
        language: "English",
        trailer: "https://youtube.com/watch?v=xH-NonWXRQs",
        bigPoster: "http://i3.ytimg.com/vi/xH-NonWXRQs/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/xH-NonWXRQs/hqdefault.jpg",
    },
    {
        title: "The Evil Within",
        year: 2017,
        categories: ["Horror"],
        summary: "The mentally handicapped thirty year-old man Dennis lives with his older brother John. When John decorates his room with an antique mirror, Dennis has nightmares and finds evil in his reflection. His reflected image forces him to kill people including his beloved ice-cream seller Susan and Dennis becomes a serial-killer. Meanwhile John's girlfriend Lydia decides to move in together with John and Dennis ignoring the threat of her brother-in-law.",
        imdbId: "tt0339736",
        imdbRating: 5.5,
        runtime: 98,
        language: "English",
        trailer: "https://youtube.com/watch?v=k2Ii4AaiBKI",
        bigPoster: "http://i3.ytimg.com/vi/k2Ii4AaiBKI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/k2Ii4AaiBKI/hqdefault.jpg",
    },
    {
        title: "Kickboxer: Vengeance",
        year: 2016,
        categories: ["Action", "Crime", "Drama", "Sport"],
        summary: "Eric and Kurt Sloane are the descendants of a well-known Venice, California-based family of martial artists. Kurt has always been in older brother, Eric's shadow, as he lacks the instincts needed to become a champion. Against Kurt's concerns, Eric accepts a paid offer and travels to Thailand to challenge the Muay Thai champion Tong Po and fails with dire consequences. Kurt sets out for revenge. He trains with his brother's mentor, Durand, for a Muay Thai fight against the merciless champion, Tong Po. Durand first thinks Kurt is impossible to train, but through a series of spiritual exercises and tests, Durand discovers that Kurt has a deeper strength that will carry him through his final showdown with Tong Po.",
        imdbId: "tt3082898",
        imdbRating: 4.9,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=oSzJUeZ072E",
        bigPoster: "http://i3.ytimg.com/vi/oSzJUeZ072E/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/oSzJUeZ072E/hqdefault.jpg",
    },
    {
        title: "Gold",
        year: 2017,
        categories: ["Adventure", "Drama", "History"],
        summary: "Amazon rainforest, 1538. King Carlos V de España y I de Alemania sends a group of Spanish soldiers to the new continent to locate Teziutlan, a legendary city created with gold, to claim it to the Spanish Empire. Alone in the rainforest and without a help, soldiers face not only indigenous tribes but the manifest hate themselves by their respective birth places. Leaded by old Don Gonzalo, married with young Doña Ana, his aging and weak health turns in danger Ana, who is disputed by Alférez Gorriamendi, Gonzalo's right-hand, and soldier Martín Dávila. After to realize that Viceroy of Port Prince has send another expedition looking for them leaded by Juan Medrano after to accuse Don Gonzalo of treason, Dávila, Gorriamendi and other soldiers as Sargento Bastaurrés and Barbate must decide if fight against Medrano's and his men or continue until Teziutlan. But the rivalry and hate between them will reveal more dangerous than the own rainforest and the indigenous tribes.",
        imdbId: "tt5162658",
        imdbRating: 5.7,
        runtime: 103,
        language: "English",
        trailer: "https://youtube.com/watch?v=gdLXPv5NsA4",
        bigPoster: "http://i3.ytimg.com/vi/gdLXPv5NsA4/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/gdLXPv5NsA4/hqdefault.jpg",
    },
    {
        title: "Naked Ambition 2",
        year: 2014,
        categories: ["Comedy"],
        summary: "A sex comedy which parodies Japanese adult film industry through various iconic scenes with exaggerated expressions.",
        imdbId: "tt3740242",
        imdbRating: 4.8,
        runtime: 107,
        language: "English",
        trailer: "https://youtube.com/watch?v=LwbHoNft3o8",
        bigPoster: "http://i3.ytimg.com/vi/LwbHoNft3o8/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/LwbHoNft3o8/hqdefault.jpg",
    },
    {
        title: "Monster High: Electrified",
        year: 2017,
        categories: ["Animation"],
        summary: "When Clawdeen dreams of opening a salon made for monsters and normies, Frankie has the perfect place - an abandoned power station outside town. But the idea sparks negative voltage when Moanica plots to ruin the whole thing, and replace the celebration with something a little more... shocking!",
        imdbId: "tt6536944",
        imdbRating: 5.8,
        runtime: 71,
        language: "English",
        trailer: "https://youtube.com/watch?v=ixjv4Qt0mxY",
        bigPoster: "http://i3.ytimg.com/vi/ixjv4Qt0mxY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/ixjv4Qt0mxY/hqdefault.jpg",
    },
    {
        title: "Open Season: Scared Silly",
        year: 2015,
        categories: ["Action", "Adventure", "Animation", "Comedy", "Family"],
        summary: 'OPEN SEASON: SCARED SILLY opens with Elliot telling a campfire story about the legend of the Wailing Wampus Werewolf that lives in Timberline National Forest. Domesticated Boog is terrified by the story and decides to "chicken out" of their annual summer camping trip until he knows the werewolf is gone. Determined to help Boog overcome his fears, Elliot and their woodland friends band together to scare the fear out of Boog and uncover the mystery of the Wailing Wampus Werewolf.',
        imdbId: "tt4938374",
        imdbRating: 5.1,
        runtime: 84,
        language: "English",
        trailer: "https://youtube.com/watch?v=p-KLqJ2ZXbI",
        bigPoster: "http://i3.ytimg.com/vi/p-KLqJ2ZXbI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/p-KLqJ2ZXbI/hqdefault.jpg",
    },
    {
        title: "The Ridiculous 6",
        year: 2015,
        categories: ["Action", "Comedy", "Western"],
        summary: "A white man, Tommy, raised by Indians is approached by his long lost father who tells him he needs $50,000 or he'll die at the hands of his former gang. Tommy goes on an incredible and ridiculous journey picking up his other 5 new brothers on the way in a race to save their dad.",
        imdbId: "tt2479478",
        imdbRating: 4.8,
        runtime: 119,
        language: "English",
        trailer: "https://youtube.com/watch?v=qUp7Qgimn38",
        bigPoster: "http://i3.ytimg.com/vi/qUp7Qgimn38/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/qUp7Qgimn38/hqdefault.jpg",
    },
    {
        title: "The Big Wedding",
        year: 2013,
        categories: ["Action", "Comedy", "Drama", "Romance"],
        summary: "Don and Ellie were once married and have two children, Lyla and Jared. They adopt a boy from Colombia, Alejandro. Eventually they would divorce, Ellie would move away and Don would hook up with Bebe, Ellie's best friend. When Alejandro is about to get married, he informs Don and Ellie that he never told his natural mother who is so traditional that they got divorced. And she is coming for the wedding so he asks them if they can pretend to still be married. Don and Ellie reluctantly agree to it and Bebe moves out who is also upset that Don doesn't want to commit. Lyla who is married is going through a rough patch in her marriage. And Jared who hasn't had much luck with women finds himself attracted to Alejandro's extremely sensual sister, Nuria.",
        imdbId: "tt1931435",
        imdbRating: 5.6,
        runtime: 0,
        language: "English",
        trailer: "https://youtube.com/watch?v=SnD2EacXk0E",
        bigPoster: "http://i3.ytimg.com/vi/SnD2EacXk0E/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/SnD2EacXk0E/hqdefault.jpg",
    },
    {
        title: "Dragonfyre",
        year: 2013,
        categories: ["Action", "Adventure", "Fantasy"],
        summary: "A battle-weary ex-Special Forces Operative buys a ranch in remote American West to flee from the world, and encounters a strange series of trespassers, including a beautiful elf princess and a Native American mystic and Orcs. When the Orcs invade his property, John must give up his isolation to become a hero, before the Orcs unleash their dragon god on our world.",
        imdbId: "tt2333508",
        imdbRating: 3.4,
        runtime: 97,
        language: "English",
        trailer: "https://youtube.com/watch?v=6I0OAI3wqIY",
        bigPoster: "http://i3.ytimg.com/vi/6I0OAI3wqIY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/6I0OAI3wqIY/hqdefault.jpg",
    },
    {
        title: "The Comedian",
        year: 2016,
        categories: ["Action", "Comedy"],
        summary: "Jackie (Robert DeNiro) is a comic icon, attempting to reinvent himself despite his audience only wanting to know him as a television character he played earlier in his career. After accosting an audience member, Jackie is sentenced to community service where he meets Harmony Schiltz (Leslie Mann).",
        imdbId: "tt1967614",
        imdbRating: 5.8,
        runtime: 120,
        language: "English",
        trailer: "https://youtube.com/watch?v=QJit_DU2XhM",
        bigPoster: "http://i3.ytimg.com/vi/QJit_DU2XhM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/QJit_DU2XhM/hqdefault.jpg",
    },
    {
        title: "Submergence",
        year: 2017,
        categories: ["Drama", "Romance", "Thriller"],
        summary: "In a room with no windows on the eastern coast of Africa, a Scotsman, James More, is held captive by jihadist fighters. Thousands of miles away in the Greenland Sea, Danielle Flinders prepares to dive in a submersible to the ocean floor. In their confines they are drawn back to the Christmas of the previous year, where a chance encounter on a beach in France led to an intense and enduring romance.",
        imdbId: "tt3563262",
        imdbRating: 5.4,
        runtime: 112,
        language: "English",
        trailer: "https://youtube.com/watch?v=KvCYgAjP08M",
        bigPoster: "http://i3.ytimg.com/vi/KvCYgAjP08M/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/KvCYgAjP08M/hqdefault.jpg",
    },
    {
        title: "You Don't Mess with the Zohan",
        year: 2008,
        categories: ["Action", "Comedy"],
        summary: "Zohan Dvir works as a Special Agent and lives with his orthodox parents in Israel. He wants to give up this life full of dangerous encounters with Palestinians. While in the process of apprehending a Palestinian activist known simply as the Phantom, he fakes his death, hides in a dog-kennel on a plane bound for New York, and decides to try his hand as a hair-stylist. He is refused employment initially, but when he offers to work for free, Dahlia hires him as a cleaner. When a hair-stylist named Debbie quits, Zohan replaces her, winning over elderly female clientèle, and falling in love with Dahlia herself. Before Zohan could propose to her, Dahlia's landlord, Walbridge, who has been raising rents regularly, hires skinhead goons to terrorize the neighborhood, creates misunderstandings between Jews, Muslims, Arabs, and Palestinians, and drives them out, so as to enable him to construct a new building which is topped by a roller coaster. When Zohan decides to confront these skinheads, he...",
        imdbId: "tt0960144",
        imdbRating: 5.5,
        runtime: 113,
        language: "English",
        trailer: "https://youtube.com/watch?v=u_I1cW14Qlg",
        bigPoster: "http://i3.ytimg.com/vi/u_I1cW14Qlg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/u_I1cW14Qlg/hqdefault.jpg",
    },
    {
        title: "New World OrdeRx",
        year: 2013,
        categories: ["Action", "Drama", "Sci-Fi"],
        summary: 'In a dystopian future where pain and emotion have been suppressed by a government-issued drug called Torpase, Joshua Barrett (Tommy Martin) coasts through the monotony of his repetitive, workaday life. But when he\'s kidnapped by a rebellious priest (Richard Hackel), Joshua is exposed to a world beyond Torpase, changing everything he thought he knew about what it means to live. Also starring Louie Lawless, Amy Hunt, and Kyle Dal Santo, "Cheery Point" examines the necessity of pain and despair and "covers a wide range of possibilities that this country, as a whole, could face" (IMDb review).',
        imdbId: "tt2298274",
        imdbRating: 2.4,
        runtime: 128,
        language: "English",
        trailer: "https://youtube.com/watch?v=w4McHSYigW0",
        bigPoster: "http://i3.ytimg.com/vi/w4McHSYigW0/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/w4McHSYigW0/hqdefault.jpg",
    },
    {
        title: "Red Billabong",
        year: 2016,
        categories: ["Action", "Adventure", "Comedy", "Horror", "Thriller"],
        summary: "In the Australian Outback, two brothers discover old secrets and family lies. As their friends start to go missing they fear they are being stalked by someone or something from their worst nightmares - But is it just - A story? A legend? A hoax? Or is it real?",
        imdbId: "tt4011010",
        imdbRating: 4,
        runtime: 113,
        language: "English",
        trailer: "https://youtube.com/watch?v=64fPRm52e5o",
        bigPoster: "http://i3.ytimg.com/vi/64fPRm52e5o/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/64fPRm52e5o/hqdefault.jpg",
    },
    {
        title: "Monster Family",
        year: 2017,
        categories: ["Animation", "Comedy", "Family", "Horror"],
        summary: "Despite the title, the Wishbone family are far from happy. In an attempt to reconnect as a family, Mum and Emma plan a fun night out. However, her plan backfires when an evil witch curses them, and they're all turned into Monsters.",
        imdbId: "tt6572702",
        imdbRating: 4.7,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=-HkkMm-I86o",
        bigPoster: "http://i3.ytimg.com/vi/-HkkMm-I86o/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/-HkkMm-I86o/hqdefault.jpg",
    },
    {
        title: "Bullet Head",
        year: 2017,
        categories: ["Crime", "Drama", "Thriller"],
        summary: "Three career criminals find themselves trapped in a warehouse with the law closing in and an even worse threat waiting inside - a nigh unstoppable killer dog.",
        imdbId: "tt6204340",
        imdbRating: 5.3,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=Ym_SB86o3Rg",
        bigPoster: "http://i3.ytimg.com/vi/Ym_SB86o3Rg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/Ym_SB86o3Rg/hqdefault.jpg",
    },
    {
        title: "Still/Born",
        year: 2017,
        categories: ["Horror", "Thriller"],
        summary: "Mary, a new mother, gives birth to twins, but only one of them is alive. While taking care of her living child, Adam, she suspects that something, a supernatural entity, has chosen him and will stop at nothing to take him from her.",
        imdbId: "tt6087426",
        imdbRating: 5.3,
        runtime: 87,
        language: "English",
        trailer: "https://youtube.com/watch?v=AKdgnX_LsOQ",
        bigPoster: "http://i3.ytimg.com/vi/AKdgnX_LsOQ/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/AKdgnX_LsOQ/hqdefault.jpg",
    },
    {
        title: "Killing Hasselhoff",
        year: 2017,
        categories: ["Comedy"],
        summary: "A man in a high stakes celebrity death pool quickly loses everything - his business, his bank account, his home, his fiancé. He snaps, then realizes the only way to get his life back on track. He'll have to murder his own celebrity. He'll have to kill Hasselhoff.",
        imdbId: "tt2967226",
        imdbRating: 4.3,
        runtime: 80,
        language: "English",
        trailer: "https://youtube.com/watch?v=IQYLBXW7ILw",
        bigPoster: "http://i3.ytimg.com/vi/IQYLBXW7ILw/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/IQYLBXW7ILw/hqdefault.jpg",
    },
    {
        title: "Dark Crimes",
        year: 2016,
        categories: ["Crime", "Drama", "Thriller"],
        summary: 'A murder investigation of a slain businessman turns to clues found in an author\'s book about an eerily similar crime. Based on the 2008 article "True Crimes - A Postmodern Murder Mystery" by David Grann.',
        imdbId: "tt1901024",
        imdbRating: 5,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=5WWC0GTP08w",
        bigPoster: "http://i3.ytimg.com/vi/5WWC0GTP08w/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/5WWC0GTP08w/hqdefault.jpg",
    },
    {
        title: "Red Dawn",
        year: 2012,
        categories: ["Action", "Sci-Fi", "Thriller", "War"],
        summary: "The city of Spokane, Washington is awakened by a North Korean paratrooper invasion. Marine Corps veteran Jed Eckert and his civilian brother, Matt, escape with a group of friends to an isolated cabin in the woods, where they witness the execution of their father at the hands of the ruthless Captain Cho. The brothers unite with their friends to form a guerrilla resistance group--the Wolverines--to drive the invaders from their home.",
        imdbId: "tt1234719",
        imdbRating: 5.4,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=nGoe7BdGdlg",
        bigPoster: "http://i3.ytimg.com/vi/nGoe7BdGdlg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/nGoe7BdGdlg/hqdefault.jpg",
    },
    {
        title: "The Last Face",
        year: 2016,
        categories: ["Drama"],
        summary: "A director (Charlize Theron) of an international aid agency in Africa meets a relief aid doctor (Javier Bardem) amidst a political/social revolution, and together face tough choices surrounding humanitarianism and life through civil unrest.",
        imdbId: "tt3286560",
        imdbRating: 4.7,
        runtime: 130,
        language: "English",
        trailer: "https://youtube.com/watch?v=e3E4mPdFG98",
        bigPoster: "http://i3.ytimg.com/vi/e3E4mPdFG98/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/e3E4mPdFG98/hqdefault.jpg",
    },
    {
        title: "The Possession",
        year: 2012,
        categories: ["Action", "Horror", "Thriller"],
        summary: "The basketball coach Clyde and his wife Stephanie divorced a couple of months ago and their teenage daughter Hannah and the girl Emily 'Em' live with their mother and spend the weekends with their father. One day, Clyde stops his car in a yard sale and Em buys an antique carved box and becomes obsessed with it. Em finds the hidden lock and releases an evil spirit that possesses her. Soon Clyde discovers that Em has a problem, but his annoying ex-wife and her boyfriend Brett do not pay attention to him and get a restraining order against Clyde. Clyde seeks out Professor McMannis and when he sees the box, he explains that it is a Dibbuk Box, where a fiend is trapped inside. He also explains that the box should not be open; otherwise the person will be possessed by the spirit. Now Clyde travels to a Jewish community in New York and the rabbi's son Tzadok returns with him expecting to exorcise Em to save the girl.",
        imdbId: "tt0431021",
        imdbRating: 5.9,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=Sxo3Wib31uE",
        bigPoster: "http://i3.ytimg.com/vi/Sxo3Wib31uE/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/Sxo3Wib31uE/hqdefault.jpg",
    },
    {
        title: "Battle of the Year",
        year: 2013,
        categories: ["Action", "Drama", "Music"],
        summary: "The producer Dante Graham promotes a group of b-boys expecting to bring the Battle of the Year Trophy back to the USA that have not won it in fifteen years. He hires his friend and former basketball coach Jason Blake that grieves the loss of his wife and son to prepare his team. Blake fires the whole team since they do not have motivation and decides to select a new group of dancers under the nickname of Dream Team. He also hires the youngster Franklyn and the choreographer of break-dance Stacy to help him. Along the months, Blake tries to implement teamwork and works hard with the group. In the competition in France, he has a great surprise.",
        imdbId: "tt1532958",
        imdbRating: 5.1,
        runtime: 110,
        language: "English",
        trailer: "https://youtube.com/watch?v=mzkZL-3A4ac",
        bigPoster: "http://i3.ytimg.com/vi/mzkZL-3A4ac/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/mzkZL-3A4ac/hqdefault.jpg",
    },
    {
        title: "Kill Command",
        year: 2016,
        categories: ["Action", "Horror", "Sci-Fi", "Thriller"],
        summary: "Set in a near future, technology-reliant society is creating killing machines. Against this backdrop an elite Marine unit is helicoptered in to a remote, off-the-grid island training facility, to test the capabilities of the latest prototypes. They set up positions and make short work of the AI targets in the killing field. However, overnight their sentry goes missing, and when they find the corpse the next day they find themselves in the killing field and the tables have turned. The Marines fight to survive on an island that is overrun by an enemy intelligence far beyond their predecessors, which learns from their every move.",
        imdbId: "tt2667380",
        imdbRating: 5.7,
        runtime: 99,
        language: "English",
        trailer: "https://youtube.com/watch?v=TPLEjs7im9c",
        bigPoster: "http://i3.ytimg.com/vi/TPLEjs7im9c/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/TPLEjs7im9c/hqdefault.jpg",
    },
    {
        title: "Viking Legacy",
        year: 2016,
        categories: ["Action", "Adventure"],
        summary: "In ancient times, there were seven sacred scrolls believed to grant power and prosperity to those who possessed them. Prophecy told that a child born in pure Royal blood would one day harness power and rule over the nations. As men fought to claim the scrolls, Europe was pushed to the brink of war. In order to maintain peace, a Celtic King, the Father of a pure blood child, obtained the scrolls and gave them to the Christian Council for safe keeping. As word of the King's actions spread, a warlord hell - bent on finding the scrolls murdered him in cold blood. And so, the King's Daughter, like the scrolls, was taken into hiding until the day that the prophecy could be fulfilled.",
        imdbId: "tt5555554",
        imdbRating: 2.5,
        runtime: 83,
        language: "English",
        trailer: "https://youtube.com/watch?v=lv6RtmzwkYI",
        bigPoster: "http://i3.ytimg.com/vi/lv6RtmzwkYI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/lv6RtmzwkYI/hqdefault.jpg",
    },
    {
        title: "Phoenix Forgotten",
        year: 2017,
        categories: ["Horror", "Mystery", "Sci-Fi", "Thriller"],
        summary: "Phoenix Forgotten tells the story of three teens who went into the desert shortly after the incident, hoping to document the strange events occurring in their town. They disappeared that night, and were never seen again. Now, on the twentieth anniversary of their disappearance, unseen footage has finally been discovered, chronicling the final hours of their fateful expedition. For the first time ever, the truth will be revealed.",
        imdbId: "tt6574272",
        imdbRating: 5.2,
        runtime: 87,
        language: "English",
        trailer: "https://youtube.com/watch?v=yJW1m1UgJjY",
        bigPoster: "http://i3.ytimg.com/vi/yJW1m1UgJjY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/yJW1m1UgJjY/hqdefault.jpg",
    },
    {
        title: "Drones",
        year: 2013,
        categories: ["Action", "Thriller"],
        summary: "Two Airmen are tasked with deciding the fate of a terrorist with a single push of a button. As the action plays out in real time, their window to use a deadly military drone on the target slowly closes. With time running out, the Airmen begin to question what the real motives are behind the ordered lethal attack.",
        imdbId: "tt2179027",
        imdbRating: 4.5,
        runtime: 82,
        language: "English",
        trailer: "https://youtube.com/watch?v=2Ma5tUgfJR4",
        bigPoster: "http://i3.ytimg.com/vi/2Ma5tUgfJR4/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/2Ma5tUgfJR4/hqdefault.jpg",
    },
    {
        title: "Let Her Out",
        year: 2016,
        categories: ["Horror", "Sci-Fi", "Thriller"],
        summary: 'Let Her Out follows Helen, a bike courier who suffers a traumatic accident. As she recovers, she begins to experience strange episodic-black outs, hallucinations, and night terrors-that lead her to discover that she has a tumor, a benign growth that is the remnants of a "vanishing twin" absorbed in utero. Over time, the tumor manifests itself as the dark and demented version of a stranger. As Helen\'s emotional and psychological state begins to deteriorate further and further, she begins to act out in psychotic episodes that are influenced by her evil twin - making her a danger to herself and her best friend, Molly.',
        imdbId: "tt5810122",
        imdbRating: 4.4,
        runtime: 89,
        language: "English",
        trailer: "https://youtube.com/watch?v=xqTeAlzawhs",
        bigPoster: "http://i3.ytimg.com/vi/xqTeAlzawhs/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/xqTeAlzawhs/hqdefault.jpg",
    },
    {
        title: "Freetown",
        year: 2015,
        categories: ["Action", "Drama", "Thriller", "War"],
        summary: "Caught in the middle of a brutal civil war, six Liberian missionaries in Monrovia flee the widespread violence of their native country. Their destination: Freetown, Sierra Leone. With the help of local church leader Phillip Abubakar, the missionaries make the difficult journey, only to have their troubles compounded by a rebel fighter bent on killing one of their own.",
        imdbId: "tt3735554",
        imdbRating: 4.7,
        runtime: 113,
        language: "English",
        trailer: "https://youtube.com/watch?v=HRn5lnG13xc",
        bigPoster: "http://i3.ytimg.com/vi/HRn5lnG13xc/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/HRn5lnG13xc/hqdefault.jpg",
    },
    {
        title: "Vendetta",
        year: 2013,
        categories: ["Action", "Thriller"],
        summary: "Special ops interrogation officer Jimmy Vickers tracks down a gang who slaughtered his parents. With police closing in & his old unit on his trail, he has to to evade capture long enough to complete his gruesome crusade.",
        imdbId: "tt2572632",
        imdbRating: 5.9,
        runtime: 106,
        language: "English",
        trailer: "https://youtube.com/watch?v=J9X0pEsJshU",
        bigPoster: "http://i3.ytimg.com/vi/J9X0pEsJshU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/J9X0pEsJshU/hqdefault.jpg",
    },
    {
        title: "Justice",
        year: 2017,
        categories: ["Western"],
        summary: "It's 1868 and the war has been over for three years. An old abandoned mine is now being transformed into a military stronghold by a corrupt Mayor and band of blood thirsty outlaws whom are a part of a larger web hell-bent on a re-surge of the civil war. When a US Marshal, James McCord comes to town only to find out that his brother has been murdered, his search for the killer takes him on life or death struggle for a much greater cause.",
        imdbId: "tt5143890",
        imdbRating: 4,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=6s47YZATefU",
        bigPoster: "http://i3.ytimg.com/vi/6s47YZATefU/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/6s47YZATefU/hqdefault.jpg",
    },
    {
        title: "Outrage Coda",
        year: 2017,
        categories: ["Action", "Crime", "Drama"],
        summary: "Five years after surviving the all-out war between the Sanno and Hanabishi crime families, former yakuza boss Otomo now works in South Korea for Mr. Chang, a renowned fixer whose influence extends into Japan. A relatively minor incident causes tensions to rise between Chang Enterprises and the faraway powerful Hanabishi. The growing conflict gets out of hand and ignites a ferocious power struggle among the top echelons of the Hanabishi. When eventually Chang's life is endangered, devoted yakuza Otomo returns to Japan to settle things once and for all.",
        imdbId: "tt6293042",
        imdbRating: 5.9,
        runtime: 104,
        language: "English",
        trailer: "https://youtube.com/watch?v=ZQxj3sz6XCI",
        bigPoster: "http://i3.ytimg.com/vi/ZQxj3sz6XCI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/ZQxj3sz6XCI/hqdefault.jpg",
    },
    {
        title: "The Last Song",
        year: 2010,
        categories: ["Action", "Drama", "Family", "Music", "Romance"],
        summary: "Ronnie's (Miley Cyrus) and her younger brother, Jonah's, parents are divorced. They live with their mother until this summer when they are sent to live with their father (Greg Kinnear) in a small town on the beach. Ronnie resents her father and has no intention of being friendly or even talking to him for the summer. But after meeting a handsome guy and beginning to fall in love, Ronnie starts rediscovering her love for music, something she shares with her father. Reconnecting with music revives a kinship with her father which proves to be the most important relationship she may ever experience.",
        imdbId: "tt1294226",
        imdbRating: 5.9,
        runtime: 0,
        language: "English",
        trailer: "https://youtube.com/watch?v=vZH0Nf4KLBo",
        bigPoster: "http://i3.ytimg.com/vi/vZH0Nf4KLBo/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/vZH0Nf4KLBo/hqdefault.jpg",
    },
    {
        title: "Walking Out",
        year: 2017,
        categories: ["Adventure", "Drama", "Mystery", "Thriller"],
        summary: 'David (Josh Wiggins), an urban teenager, journeys to rural Montana to hunt big game with his estranged, "off the grid" father, Cal (Matt Bomer). As they ascend deep into the wilderness, father and son struggle to connect on any level, until a brutal encounter leaves them both with serious injuries, forcing them into a struggle to survive. Based on the American short story "Walking Out.',
        imdbId: "tt5420886",
        imdbRating: 5.8,
        runtime: 95,
        language: "English",
        trailer: "https://youtube.com/watch?v=DAMmyBATXzg",
        bigPoster: "http://i3.ytimg.com/vi/DAMmyBATXzg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/DAMmyBATXzg/hqdefault.jpg",
    },
    {
        title: "WEAPONiZED",
        year: 2016,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: 'A damaged homicide detective (Johnny Messner) must prevent a grieving father from unleashing a "robotic virus" that he believes will destroy the terrorist cell that murdered his son, but at an unimaginable cost.',
        imdbId: "tt4776564",
        imdbRating: 4.4,
        runtime: 91,
        language: "English",
        trailer: "https://youtube.com/watch?v=OLgpUebFYTM",
        bigPoster: "http://i3.ytimg.com/vi/OLgpUebFYTM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/OLgpUebFYTM/hqdefault.jpg",
    },
    {
        title: "The Bling Ring",
        year: 2013,
        categories: ["Action", "Biography", "Crime", "Drama"],
        summary: "Inspired by actual events, a group of fame-obsessed teenagers use the internet to track celebrities' whereabouts in order to rob their homes.",
        imdbId: "tt2132285",
        imdbRating: 5.6,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=Q4LzhgExvrc",
        bigPoster: "http://i3.ytimg.com/vi/Q4LzhgExvrc/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/Q4LzhgExvrc/hqdefault.jpg",
    },
    {
        title: "Bad Johnson",
        year: 2014,
        categories: ["Action", "Comedy", "Fantasy", "Romance"],
        summary: "A charismatic womanizer receives his comeuppance after his penis mysteriously leaves his body and takes human form.",
        imdbId: "tt2091325",
        imdbRating: 4.5,
        runtime: 88,
        language: "English",
        trailer: "https://youtube.com/watch?v=aJbIUYJVw3Q",
        bigPoster: "http://i3.ytimg.com/vi/aJbIUYJVw3Q/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/aJbIUYJVw3Q/hqdefault.jpg",
    },
    {
        title: "Animal",
        year: 2014,
        categories: ["Action", "Adventure", "Horror", "Mystery", "Thriller"],
        summary: "When plans for a weekend vacation hit a dead end, a group of close-knit friends find themselves stranded in unfamiliar territory, pursued by a menacing, blood thirsty predator. Holed up in an isolated cabin, tensions mount as long-buried secrets are revealed. As the body count rises, the group must put their differences aside and fight for survival.",
        imdbId: "tt2996684",
        imdbRating: 4.8,
        runtime: 86,
        language: "English",
        trailer: "https://youtube.com/watch?v=fljp9_0o2y0",
        bigPoster: "http://i3.ytimg.com/vi/fljp9_0o2y0/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/fljp9_0o2y0/hqdefault.jpg",
    },
    {
        title: "Capture the Flag",
        year: 2015,
        categories: ["Action", "Adventure", "Animation", "Comedy", "Family"],
        summary: "Mike Goldwing, a plucky, determined 12-year old boy, is the son and grandson of NASA astronauts. His grandfather Frank, a once revered, but now forgotten retired astronaut, lives his days isolated from his family after missing out on his big chance to fly to the moon with Neil Armstrong and Buzz Aldrin as a part of the Apollo XI mission. When an eccentric billionaire sets an evil plan to fly to the moon, steal the moon's vast mineral resources, and destroy the American flag planted by the Apollo XI team, Mike embarks on a magnificent adventure as a stowaway on the space shuttle. Accompanied by his grandfather, best friends Amy and Marty, and a clever chameleon, Mike blasts off to the moon to capture the flag and reunite his family.",
        imdbId: "tt3896100",
        imdbRating: 5.9,
        runtime: 94,
        language: "English",
        trailer: "https://youtube.com/watch?v=67YfSzkmDgw",
        bigPoster: "http://i3.ytimg.com/vi/67YfSzkmDgw/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/67YfSzkmDgw/hqdefault.jpg",
    },
    {
        title: "Primal Rage",
        year: 2018,
        categories: ["Horror"],
        summary: "Lost deep in the forest of the Pacific Northwest, Ashley and Max Carr are stalked by a terrifying creature that might be Bigfoot. Soon they find themselves embroiled in a strange land of Native American myth and legend turned real. Hopelessly trying to survive, with a handful of unsavory locals, they must fight back against this monster in a desperate battle of life or death.",
        imdbId: "tt5688868",
        imdbRating: 4.9,
        runtime: 106,
        language: "English",
        trailer: "https://youtube.com/watch?v=m_c-G_6JKzA",
        bigPoster: "http://i3.ytimg.com/vi/m_c-G_6JKzA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/m_c-G_6JKzA/hqdefault.jpg",
    },
    {
        title: "From the Dark",
        year: 2014,
        categories: ["Action", "Horror", "Thriller"],
        summary: "A couple on a trip through the Irish countryside find themselves hunted by a creature who only attacks at night.",
        imdbId: "tt4030442",
        imdbRating: 4.8,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=kKsceLZu_wg",
        bigPoster: "http://i3.ytimg.com/vi/kKsceLZu_wg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/kKsceLZu_wg/hqdefault.jpg",
    },
    {
        title: "Hammer of the Gods",
        year: 2013,
        categories: ["Action", "Adventure", "History"],
        summary: "A high energy, high concept, stylish action epic set in the Norse world sees a passionate young man transform into a brutal warrior as he travels the unforgiving British landscape in search of his long lost brother Hakan The Ferrocious who his people are relying on to restore order to their kingdom following the bloody death of their king.",
        imdbId: "tt2193418",
        imdbRating: 4.5,
        runtime: 99,
        language: "English",
        trailer: "https://youtube.com/watch?v=Kcw3cmhgntI",
        bigPoster: "http://i3.ytimg.com/vi/Kcw3cmhgntI/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/Kcw3cmhgntI/hqdefault.jpg",
    },
    {
        title: "Money",
        year: 2016,
        categories: ["Crime", "Mystery", "Thriller"],
        summary: "Two wealthy businessmen are about to get away with $5 million in ill-gotten money until their plans are revealed by an uninvited house guest.",
        imdbId: "tt4715356",
        imdbRating: 5.7,
        runtime: 86,
        language: "English",
        trailer: "https://youtube.com/watch?v=",
        bigPoster: "http://i3.ytimg.com/vi//maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi//hqdefault.jpg",
    },
    {
        title: "Russell Madness",
        year: 2015,
        categories: ["Action", "Drama", "Family", "Sport"],
        summary: "RUSSELL MADNESS tells the story of Russell, an undersized but big-hearted terrier who dreams of having a family of his own. After running away from his pet store, Russell gets taken in by The Ferraros, a family desperate to revive their grandfather's pro wrestling arena. That's when they discover their new pet pooch has incredible wrestling skills. With help from his coach, Hunk, a savvy and hilarious monkey, Russell rockets to the top of the pro wrestling world and becomes a famous sports superstar. But when a dishonest promoter double-crosses the Ferraros, Russell will face his biggest challenge and discover that the strongest tag team is family.",
        imdbId: "tt4257950",
        imdbRating: 4.3,
        runtime: 92,
        language: "English",
        trailer: "https://youtube.com/watch?v=dVH9ULo4mzQ",
        bigPoster: "http://i3.ytimg.com/vi/dVH9ULo4mzQ/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/dVH9ULo4mzQ/hqdefault.jpg",
    },
    {
        title: "A Good Man",
        year: 2014,
        categories: ["Action", "Crime", "Thriller"],
        summary: "After an illustrious special ops career ends in disaster, Alexander (Seagal) goes off the grid and attempts to lead a quiet life as a handyman at an apartment complex in Romania. But when one of his tenants and her family fall under the thumb of a local gangster, Alexander is dragged into an all-out war between rival Chinese and Russian gangs; forcing him to not only defend the family, but bringing him face to face with an old foe, and giving him one more chance to reconcile his past.",
        imdbId: "tt3480556",
        imdbRating: 4.7,
        runtime: 100,
        language: "English",
        trailer: "https://youtube.com/watch?v=pYcobufHJAA",
        bigPoster: "http://i3.ytimg.com/vi/pYcobufHJAA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/pYcobufHJAA/hqdefault.jpg",
    },
    {
        title: "Haunter",
        year: 2013,
        categories: ["Action", "Horror", "Mystery", "Thriller"],
        summary: "SPOILER: In 1985, on the eve of her sixteenth birthday, Lisa discovers that she is stuck in time, living the same day over and over with her parents Bruce and Carol and her little brother Robbie. Soon she learns that they are dead and trapped on the day that they were murdered but she finds that she can contact other people. Out of the blue, a stranger comes to her house telling that he is going to fix the telephone line but indeed to threaten her to stop the contacts. Lisa finds that she is contacting victims of the killer in different timelines including the future, and the killer's name is Edgar. Will be possible to Lisa to stop the evil Edgar?",
        imdbId: "tt2345567",
        imdbRating: 5.9,
        runtime: 97,
        language: "English",
        trailer: "https://youtube.com/watch?v=sClAdBHrZNg",
        bigPoster: "http://i3.ytimg.com/vi/sClAdBHrZNg/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/sClAdBHrZNg/hqdefault.jpg",
    },
    {
        title: "Daredevil",
        year: 2003,
        categories: ["Action", "Crime", "Drama", "Fantasy", "Sci-Fi"],
        summary: 'Fate deals young orphan Matt Murdock a strange hand when he is doused with hazardous waste. The accident leaves Matt blind but also gives him a heightened "radar sense" that allows him to "see" far better than any man. Years later Murdock has grown into a man and becomes a respected criminal attorney. But after he\'s done his "day job" Matt takes on a secret identity as "The Man Without Fear," Daredevil, the masked avenger that patrols the neighborhood of Hell\'s Kitchen and New York City to combat the injustice that he cannot tackle in the courtroom.',
        imdbId: "tt0287978",
        imdbRating: 5.3,
        runtime: 103,
        language: "English",
        trailer: "https://youtube.com/watch?v=2XjLK8pvEMw",
        bigPoster: "http://i3.ytimg.com/vi/2XjLK8pvEMw/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/2XjLK8pvEMw/hqdefault.jpg",
    },
    {
        title: "The Possession of Michael King",
        year: 2014,
        categories: ["Action", "Horror"],
        summary: "Michael King (Shane Johnson) doesn't believe in God or the Devil. Following the sudden death of his wife, Michael decides to make his next film about the search for the existence of the supernatural, making himself the center of the experiment - allowing demonologists, necromancers, and various practitioners of the occult to try the deepest and darkest spells and rituals they can find on him - in the hopes that when they fail, he'll once and for all have proof that religion, spiritualism, and the paranormal are nothing more than myth. But something does happen. An evil and horrifying force has taken over Michael King. And it will not let him go.",
        imdbId: "tt2282016",
        imdbRating: 5.7,
        runtime: 83,
        language: "English",
        trailer: "https://youtube.com/watch?v=dbUMYgKIvik",
        bigPoster: "http://i3.ytimg.com/vi/dbUMYgKIvik/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/dbUMYgKIvik/hqdefault.jpg",
    },
    {
        title: "Ozzy",
        year: 2016,
        categories: ["Action", "Adventure", "Animation", "Comedy", "Family"],
        summary: "Ozzy, a friendly, peaceful beagle has his idyllic life turned upside down when the Martins leave on a long and distant trip. There's only one problem: no dogs allowed! Unable to bring their beloved Ozzy along for the ride, they settle on the next best thing, a top-of-the-line canine spa called Blue Creek. This picture perfect place turns out to be a facade constructed by its villainous owner to capture dogs. Ozzy will soon end up in the real Blue Creek, a prison for dogs, run by dogs. Ozzy will have to avoid danger and find strength in his new friends, Chester, Fronky and Doc to escape the prison and return home safely. The narrative of 'OZZY' aims to follow in the footsteps of movies which employs Pixar-like quality and fun. 'OZZY' is an animated comedy-adventure movie targeted for kids of all ages and represents family entertainment at its best. The story itself is based, almost entirely, around dogs. 'OZZY' falls into the \"prison movie\" genre with funny tributes to the great prison...",
        imdbId: "tt5770430",
        imdbRating: 5.2,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=WF5oLKwfcZA",
        bigPoster: "http://i3.ytimg.com/vi/WF5oLKwfcZA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/WF5oLKwfcZA/hqdefault.jpg",
    },
    {
        title: "Ice Age: Collision Course",
        year: 2016,
        categories: ["Action", "Adventure", "Animation", "Comedy", "Family"],
        summary: "Scrat's epic pursuit of his elusive acorn catapults him outside of Earth, where he accidentally sets off a series of cosmic events that transform and threaten the planet. To save themselves from peril, Manny, Sid, Diego, and the rest of the herd leave their home and embark on a quest full of thrills and spills, highs and lows, laughter and adventure while traveling to exotic new lands and encountering a host of colorful new characters.",
        imdbId: "tt3416828",
        imdbRating: 5.7,
        runtime: 94,
        language: "English",
        trailer: "https://youtube.com/watch?v=S0c6Jv240QQ",
        bigPoster: "http://i3.ytimg.com/vi/S0c6Jv240QQ/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/S0c6Jv240QQ/hqdefault.jpg",
    },
    {
        title: "The Twilight Saga: Breaking Dawn - Part 1",
        year: 2011,
        categories: ["Action", "Adventure", "Drama", "Fantasy", "Romance"],
        summary: "After Bella and Edward's honeymoon, things take a turn for the worse when Bella realises she is pregnant. The baby grows at an abnormally fast rate and causes many health problems to Bella. The wolf pack see the unborn child as a threat and plan to get rid of it. But the Cullens do everything they can to ensure that both Bella and the unborn child remain safe.",
        imdbId: "tt1324999",
        imdbRating: 4.9,
        runtime: 117,
        language: "English",
        trailer: "https://youtube.com/watch?v=aWzXJXqp2Ho",
        bigPoster: "http://i3.ytimg.com/vi/aWzXJXqp2Ho/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/aWzXJXqp2Ho/hqdefault.jpg",
    },
    {
        title: "Mortdecai",
        year: 2015,
        categories: ["Action", "Comedy", "Crime", "Mystery", "Romance"],
        summary: "Juggling some angry Russians, the British Mi5, his impossibly leggy wife and an international terrorist, debonair art dealer and part time rogue Charlie Mortdecai must traverse the globe armed only with his good looks and special charm in a race to recover a stolen painting rumored to contain the code to a lost bank account filled with Nazi gold.",
        imdbId: "tt3045616",
        imdbRating: 5.5,
        runtime: 107,
        language: "English",
        trailer: "https://youtube.com/watch?v=UKY3scPIMd8",
        bigPoster: "http://i3.ytimg.com/vi/UKY3scPIMd8/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/UKY3scPIMd8/hqdefault.jpg",
    },
    {
        title: "Alvin and the Chipmunks: The Road Chip",
        year: 2015,
        categories: ["Action", "Adventure", "Animation", "Comedy", "Family"],
        summary: "Through a series of misunderstandings, Alvin, Simon and Theodore come to believe that Dave is going to propose to his new girlfriend in Miami...and dump them. They have three days to get to him and stop the proposal, saving themselves not only from losing Dave but possibly from gaining a terrible stepbrother.",
        imdbId: "tt2974918",
        imdbRating: 5.1,
        runtime: 0,
        language: "English",
        trailer: "https://youtube.com/watch?v=xA6cOSEZhzM",
        bigPoster: "http://i3.ytimg.com/vi/xA6cOSEZhzM/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/xA6cOSEZhzM/hqdefault.jpg",
    },
    {
        title: "Operation Dunkirk",
        year: 2017,
        categories: ["Action", "History", "War"],
        summary: "A band of soldiers must battle their way through Nazi territory to rescue a scientist that could help turn the tide of WWII.",
        imdbId: "tt6836772",
        imdbRating: 3.4,
        runtime: 96,
        language: "English",
        trailer: "https://youtube.com/watch?v=FO0EfzLY-dk",
        bigPoster: "http://i3.ytimg.com/vi/FO0EfzLY-dk/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/FO0EfzLY-dk/hqdefault.jpg",
    },
    {
        title: "Snatched",
        year: 2017,
        categories: ["Action", "Comedy"],
        summary: "After her boyfriend dumps her on the eve of their exotic vacation, impetuous dreamer Emily Middleton persuades her ultra-cautious mother, Linda to travel with her to paradise. Polar opposites, Emily and Linda realize that working through their differences as mother and daughter - in unpredictable, hilarious fashion - is the only way to escape the wildly outrageous jungle adventure they have fallen into.",
        imdbId: "tt2334871",
        imdbRating: 4.4,
        runtime: 90,
        language: "English",
        trailer: "https://youtube.com/watch?v=9Jcsc62gdBk",
        bigPoster: "http://i3.ytimg.com/vi/9Jcsc62gdBk/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/9Jcsc62gdBk/hqdefault.jpg",
    },
    {
        title: "Hitman: Agent 47",
        year: 2015,
        categories: ["Action", "Adventure", "Crime", "Sci-Fi", "Thriller"],
        summary: "HITMAN: AGENT 47 centers on an elite assassin who was genetically engineered from conception to be the perfect killing machine, and is known only by the last two digits on the barcode tattooed on the back of his neck. He is the culmination of decades of research and forty-six earlier Agent clones -- endowing him with unprecedented strength, speed, stamina and intelligence. His latest target is a mega-corporation that plans to unlock the secret of Agent 47's past to create an army of killers whose powers surpass even his own. Teaming up with a young woman who may hold the secret to overcoming their powerful and clandestine enemies, 47 confronts stunning revelations about his own origins and squares off in an epic battle with his deadliest foe.",
        imdbId: "tt2679042",
        imdbRating: 5.7,
        runtime: 96,
        language: "English",
        trailer: "https://youtube.com/watch?v=alQlJDRnQkE",
        bigPoster: "http://i3.ytimg.com/vi/alQlJDRnQkE/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/alQlJDRnQkE/hqdefault.jpg",
    },
    {
        title: "Hot Tub Time Machine 2",
        year: 2015,
        categories: ["Action", "Comedy", "Sci-Fi"],
        summary: "When Lou finds himself in trouble, Nick and Jacob fire up the hot tub time machine in an attempt to get back to the past. But they inadvertently land in the future with Adam Jr. Now they have to alter the future in order to save the past - which is really the present.",
        imdbId: "tt2637294",
        imdbRating: 5.1,
        runtime: 93,
        language: "English",
        trailer: "https://youtube.com/watch?v=BNJ-UxlKXGY",
        bigPoster: "http://i3.ytimg.com/vi/BNJ-UxlKXGY/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/BNJ-UxlKXGY/hqdefault.jpg",
    },
    {
        title: "Grown Ups 2",
        year: 2013,
        categories: ["Action", "Comedy"],
        summary: "After having the greatest time of his life three summers ago, Lenny (Adam Sandler), decides he wants to move his family back to his hometown and have them grow up with his gang of childhood friends and their kids. But between old bullies, new bullies, schizophrenic bus drivers, drunk cops on skis, psycho grade school girlfriends and 400 costumed party crashes he finds out that sometimes crazy follows you.",
        imdbId: "tt2191701",
        imdbRating: 5.4,
        runtime: 101,
        language: "English",
        trailer: "https://youtube.com/watch?v=YhOWtVElqfw",
        bigPoster: "http://i3.ytimg.com/vi/YhOWtVElqfw/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/YhOWtVElqfw/hqdefault.jpg",
    },
    {
        title: "The Purge",
        year: 2013,
        categories: ["Action", "Horror", "Sci-Fi", "Thriller"],
        summary: "In an America wracked by crime and overcrowded prisons, the government has sanctioned an annual 12-hour period in which any and all criminal activity-including murder-becomes legal. The police can't be called. Hospitals suspend help. It's one night when the citizenry regulates itself without thought of punishment. On this night plagued by violence and an epidemic of crime, one family wrestles with the decision of who they will become when a stranger comes knocking. When an intruder breaks into James Sandin's (Ethan Hawke) gated community during the yearly lockdown, he begins a sequence of events that threatens to tear a family apart. Now, it is up to James, his wife, Mary (Lena Headey), and their kids to make it through the night without turning into the monsters from whom they hide.",
        imdbId: "tt2184339",
        imdbRating: 5.7,
        runtime: 85,
        language: "English",
        trailer: "https://youtube.com/watch?v=K0LLaybEuzA",
        bigPoster: "http://i3.ytimg.com/vi/K0LLaybEuzA/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/K0LLaybEuzA/hqdefault.jpg",
    },
    {
        title: "Clown",
        year: 2014,
        categories: ["Action", "Drama", "Fantasy", "Horror", "Thriller"],
        summary: "A little boy's birthday party gets ruined when his entertainment (clown) cancels. His father finds a clown suit and becomes the new entertainment but something is weird about it, there is an evil curse and it won't come off. He specializes in eating little kids... everything after that goes down hill.",
        imdbId: "tt1780798",
        imdbRating: 5.7,
        runtime: 100,
        language: "English",
        trailer: "https://youtube.com/watch?v=PNtZu-3di38",
        bigPoster: "http://i3.ytimg.com/vi/PNtZu-3di38/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/PNtZu-3di38/hqdefault.jpg",
    },
    {
        title: "The Legend of Hercules",
        year: 2014,
        categories: ["Action", "Adventure", "Fantasy"],
        summary: "In Ancient Greece 1200 B.C., a queen succumbs to the lust of Zeus to bear a son promised to overthrow the tyrannical rule of the king and restore peace to a land in hardship. But this prince, Hercules, knows nothing of his real identity or his destiny. He desires only one thing: the love of Hebe, Princess of Crete, who has been promised to his own brother. When Hercules learns of his greater purpose, he must choose: to flee with his true love or to fulfill his destiny and become the true hero of his time. The story behind one of the greatest myths is revealed in this action-packed epic - a tale of love, sacrifice and the strength of the human spirit.",
        imdbId: "tt1043726",
        imdbRating: 4.2,
        runtime: 0,
        language: "English",
        trailer: "https://youtube.com/watch?v=g0GMzQwO2l0",
        bigPoster: "http://i3.ytimg.com/vi/g0GMzQwO2l0/maxresdefault.jpg",
        smallPoster: "http://i3.ytimg.com/vi/g0GMzQwO2l0/hqdefault.jpg",
    },
]